services:
  app:
    image: mysociety/scotland-climate-projects-data:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/scotland_climate_projects_data      
    volumes:
      - ./:/workspaces/scotland_climate_projects_data/